### ISSUE TITLE
SolaceInternalSecurityGroup needs port 55555 opened

### ISSUE THREAD

**Issue by KenBarr** [aws-quickstart/quickstart-solace-vmr#13]
Solace VMR config-sync between primary and backup VMR requires port 55555 to be open.  If a invocation of this template does not include the VMR EC2 internal IPs within the "Allowed External Access CIDR" range then config-sync will not come up.

The SolaceInternalSecurityGroup within the Solace-VMR stack needs to expose this port independently of external access.

**Comment by vsnyc** [comment]
This is merged to master and published.
